[phases.setup]
nixPkgs = ["nodejs-18_x", "openssl"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = ["cd backend && npx prisma generate"]

[start]
cmd = "cd backend && npx prisma migrate deploy && node src/index.js"
