[phases.setup]
nixPkgs = ["nodejs-18_x", "postgresql"]

[phases.install]
cmds = ["npm ci", "npx prisma generate"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "node src/index.js"
